#
# Copyright 2015 Lucera Financial Infrastructure, LLC
#
# This software may be modified and distributed under the terms of the
# MIT license. See the LICENSE file for details.
#
PLATFORM_CPP=-D__EXTENSIONS__
PLATFORM_LIB_LD=-z text -z defs
